version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/project-groomeong/tocatoca:3.3
    build:
      context: .
      dockerfile: Dockerfile.prod
    # ports:
    #   - 3000:3000
    # env_file:
    #   - ./.env.prodmy3

  # my-database:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'groomeongprod'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306

  # my-redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379

  # elasticsearch:
  #   image: elasticsearch:7.17.0
  #   environment:
  #     discovery.type: single-node
  #   ports:
  #     - 9200:9200

  logstash:
    image: asia.gcr.io/project-groomeong/logstash:1.0
    build:
      context: .
      dockerfile: Dockerfile.logstash
