version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/project-groomeong/backend:2.0
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod

  logstash:
    image: asia.gcr.io/project-groomeong/logstash:1.1
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.logstash
